branch-defaults:
  default:
    environment: todoweb-app
    group_suffix: null
global:
  application_name: todoweb
  branch: null
  default_ec2_keyname: project
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
